### ISSUE TITLE
Why do DPM++ 2M SDE have artifcating when it used to work fine?

### ISSUE THREAD

**Issue by cantonalex** [viking1304/a1111-setup#5] opened 2024-01-07 13:47 UTC
I think its something specific to Apple Silicon.. and the flags called at runtime.

**Comment by viking1304** [comment] 2024-01-07 14:28
You probably just used some wrong settings. My advice is to come to [#prompting-help](https://discord.com/channels/1002292111942635562/1011743094309396631) on Discord where someone will help you.

Meanwhile, you can copy/paste the info that you are getting (bellow the image) so I can see whats going on.

**Comment by viking1304** [comment] 2024-01-10 10:43
I am closing this issue since that is not a bug and is not related to my script.

Feel free to open a new theme in [discussion](https://github.com/viking1304/a1111-setup/discussions), and I will try to help you with that problem. Basically, you need to use a proper combination of dimensions, sampler, cfg, and steps.

**Closed** 2024-01-10 10:44 UTC
Labels: not a bug, webui usage issue
